//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 12:47:30 PM UTC 
//

package com.anstis.pmml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import jsinterop.annotations.JsType;
import org.treblereel.j2cl.processors.annotations.GWT3Export;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;group ref="{http://www.dmg.org/PMML-4_4}CONTINUOUS-DISTRIBUTION-TYPES"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "anyDistribution",
        "gaussianDistribution",
        "poissonDistribution",
        "uniformDistribution"
})
@XmlRootElement(name = "Alternate")
@JsType
@GWT3Export
public class Alternate {

    @XmlElement(name = "AnyDistribution")
    protected AnyDistribution anyDistribution;
    @XmlElement(name = "GaussianDistribution")
    protected GaussianDistribution gaussianDistribution;
    @XmlElement(name = "PoissonDistribution")
    protected PoissonDistribution poissonDistribution;
    @XmlElement(name = "UniformDistribution")
    protected UniformDistribution uniformDistribution;

    /**
     * Gets the value of the anyDistribution property.
     *
     * @return possible object is
     * {@link AnyDistribution }
     */
    public AnyDistribution getAnyDistribution() {
        return anyDistribution;
    }

    /**
     * Sets the value of the anyDistribution property.
     *
     * @param value allowed object is
     *              {@link AnyDistribution }
     */
    public void setAnyDistribution(AnyDistribution value) {
        this.anyDistribution = value;
    }

    /**
     * Gets the value of the gaussianDistribution property.
     *
     * @return possible object is
     * {@link GaussianDistribution }
     */
    public GaussianDistribution getGaussianDistribution() {
        return gaussianDistribution;
    }

    /**
     * Sets the value of the gaussianDistribution property.
     *
     * @param value allowed object is
     *              {@link GaussianDistribution }
     */
    public void setGaussianDistribution(GaussianDistribution value) {
        this.gaussianDistribution = value;
    }

    /**
     * Gets the value of the poissonDistribution property.
     *
     * @return possible object is
     * {@link PoissonDistribution }
     */
    public PoissonDistribution getPoissonDistribution() {
        return poissonDistribution;
    }

    /**
     * Sets the value of the poissonDistribution property.
     *
     * @param value allowed object is
     *              {@link PoissonDistribution }
     */
    public void setPoissonDistribution(PoissonDistribution value) {
        this.poissonDistribution = value;
    }

    /**
     * Gets the value of the uniformDistribution property.
     *
     * @return possible object is
     * {@link UniformDistribution }
     */
    public UniformDistribution getUniformDistribution() {
        return uniformDistribution;
    }

    /**
     * Sets the value of the uniformDistribution property.
     *
     * @param value allowed object is
     *              {@link UniformDistribution }
     */
    public void setUniformDistribution(UniformDistribution value) {
        this.uniformDistribution = value;
    }
}
