//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 12:47:30 PM UTC 
//

package com.anstis.pmml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MiningSchema"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Output" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}LocalTransformations" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}ModelVerification" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.dmg.org/PMML-4_4}MODEL-ELEMENT"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MeanClusterDistances" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="algorithmName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="functionName" use="required" type="{http://www.dmg.org/PMML-4_4}MINING-FUNCTION" /&gt;
 *       &lt;attribute name="algorithmType" use="required" type="{http://www.dmg.org/PMML-4_4}ALGORITHM-TYPE" /&gt;
 *       &lt;attribute name="sampleDataSize" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isScorable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "extension",
        "miningSchema",
        "output",
        "localTransformations",
        "modelVerification",
        "anomalyDetectionModel",
        "associationModel",
        "bayesianNetworkModel",
        "baselineModel",
        "clusteringModel",
        "gaussianProcessModel",
        "generalRegressionModel",
        "miningModel",
        "naiveBayesModel",
        "nearestNeighborModel",
        "neuralNetwork",
        "regressionModel",
        "ruleSetModel",
        "sequenceModel",
        "scorecard",
        "supportVectorMachineModel",
        "textModel",
        "timeSeriesModel",
        "treeModel",
        "meanClusterDistances"
})
@XmlRootElement(name = "AnomalyDetectionModel")
public class AnomalyDetectionModel implements IPMML {

    @XmlElement(name = "Extension")
    protected List<Extension> extension;
    @XmlElement(name = "MiningSchema", required = true)
    protected MiningSchema miningSchema;
    @XmlElement(name = "Output")
    protected Output output;
    @XmlElement(name = "LocalTransformations")
    protected LocalTransformations localTransformations;
    @XmlElement(name = "ModelVerification")
    protected ModelVerification modelVerification;
    @XmlElement(name = "AnomalyDetectionModel")
    protected AnomalyDetectionModel anomalyDetectionModel;
    @XmlElement(name = "AssociationModel")
    protected AssociationModel associationModel;
    @XmlElement(name = "BayesianNetworkModel")
    protected BayesianNetworkModel bayesianNetworkModel;
    @XmlElement(name = "BaselineModel")
    protected BaselineModel baselineModel;
    @XmlElement(name = "ClusteringModel")
    protected ClusteringModel clusteringModel;
    @XmlElement(name = "GaussianProcessModel")
    protected GaussianProcessModel gaussianProcessModel;
    @XmlElement(name = "GeneralRegressionModel")
    protected GeneralRegressionModel generalRegressionModel;
    @XmlElement(name = "MiningModel")
    protected MiningModel miningModel;
    @XmlElement(name = "NaiveBayesModel")
    protected NaiveBayesModel naiveBayesModel;
    @XmlElement(name = "NearestNeighborModel")
    protected NearestNeighborModel nearestNeighborModel;
    @XmlElement(name = "NeuralNetwork")
    protected NeuralNetwork neuralNetwork;
    @XmlElement(name = "RegressionModel")
    protected RegressionModel regressionModel;
    @XmlElement(name = "RuleSetModel")
    protected RuleSetModel ruleSetModel;
    @XmlElement(name = "SequenceModel")
    protected SequenceModel sequenceModel;
    @XmlElement(name = "Scorecard")
    protected Scorecard scorecard;
    @XmlElement(name = "SupportVectorMachineModel")
    protected SupportVectorMachineModel supportVectorMachineModel;
    @XmlElement(name = "TextModel")
    protected TextModel textModel;
    @XmlElement(name = "TimeSeriesModel")
    protected TimeSeriesModel timeSeriesModel;
    @XmlElement(name = "TreeModel")
    protected TreeModel treeModel;
    @XmlElement(name = "MeanClusterDistances")
    protected MeanClusterDistances meanClusterDistances;
    @XmlAttribute(name = "modelName")
    protected String modelName;
    @XmlAttribute(name = "algorithmName")
    protected String algorithmName;
    @XmlAttribute(name = "functionName", required = true)
    protected MININGFUNCTION functionName;
    @XmlAttribute(name = "algorithmType", required = true)
    protected ALGORITHMTYPE algorithmType;
    @XmlAttribute(name = "sampleDataSize")
    protected String sampleDataSize;
    @XmlAttribute(name = "isScorable")
    protected Boolean isScorable;

    /**
     * Gets the value of the extension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the miningSchema property.
     *
     * @return possible object is
     * {@link MiningSchema }
     */
    public MiningSchema getMiningSchema() {
        return miningSchema;
    }

    /**
     * Sets the value of the miningSchema property.
     *
     * @param value allowed object is
     *              {@link MiningSchema }
     */
    public void setMiningSchema(MiningSchema value) {
        this.miningSchema = value;
    }

    /**
     * Gets the value of the output property.
     *
     * @return possible object is
     * {@link Output }
     */
    public Output getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     *
     * @param value allowed object is
     *              {@link Output }
     */
    public void setOutput(Output value) {
        this.output = value;
    }

    /**
     * Gets the value of the localTransformations property.
     *
     * @return possible object is
     * {@link LocalTransformations }
     */
    public LocalTransformations getLocalTransformations() {
        return localTransformations;
    }

    /**
     * Sets the value of the localTransformations property.
     *
     * @param value allowed object is
     *              {@link LocalTransformations }
     */
    public void setLocalTransformations(LocalTransformations value) {
        this.localTransformations = value;
    }

    /**
     * Gets the value of the modelVerification property.
     *
     * @return possible object is
     * {@link ModelVerification }
     */
    public ModelVerification getModelVerification() {
        return modelVerification;
    }

    /**
     * Sets the value of the modelVerification property.
     *
     * @param value allowed object is
     *              {@link ModelVerification }
     */
    public void setModelVerification(ModelVerification value) {
        this.modelVerification = value;
    }

    /**
     * Gets the value of the anomalyDetectionModel property.
     *
     * @return possible object is
     * {@link AnomalyDetectionModel }
     */
    public AnomalyDetectionModel getAnomalyDetectionModel() {
        return anomalyDetectionModel;
    }

    /**
     * Sets the value of the anomalyDetectionModel property.
     *
     * @param value allowed object is
     *              {@link AnomalyDetectionModel }
     */
    public void setAnomalyDetectionModel(AnomalyDetectionModel value) {
        this.anomalyDetectionModel = value;
    }

    /**
     * Gets the value of the associationModel property.
     *
     * @return possible object is
     * {@link AssociationModel }
     */
    public AssociationModel getAssociationModel() {
        return associationModel;
    }

    /**
     * Sets the value of the associationModel property.
     *
     * @param value allowed object is
     *              {@link AssociationModel }
     */
    public void setAssociationModel(AssociationModel value) {
        this.associationModel = value;
    }

    /**
     * Gets the value of the bayesianNetworkModel property.
     *
     * @return possible object is
     * {@link BayesianNetworkModel }
     */
    public BayesianNetworkModel getBayesianNetworkModel() {
        return bayesianNetworkModel;
    }

    /**
     * Sets the value of the bayesianNetworkModel property.
     *
     * @param value allowed object is
     *              {@link BayesianNetworkModel }
     */
    public void setBayesianNetworkModel(BayesianNetworkModel value) {
        this.bayesianNetworkModel = value;
    }

    /**
     * Gets the value of the baselineModel property.
     *
     * @return possible object is
     * {@link BaselineModel }
     */
    public BaselineModel getBaselineModel() {
        return baselineModel;
    }

    /**
     * Sets the value of the baselineModel property.
     *
     * @param value allowed object is
     *              {@link BaselineModel }
     */
    public void setBaselineModel(BaselineModel value) {
        this.baselineModel = value;
    }

    /**
     * Gets the value of the clusteringModel property.
     *
     * @return possible object is
     * {@link ClusteringModel }
     */
    public ClusteringModel getClusteringModel() {
        return clusteringModel;
    }

    /**
     * Sets the value of the clusteringModel property.
     *
     * @param value allowed object is
     *              {@link ClusteringModel }
     */
    public void setClusteringModel(ClusteringModel value) {
        this.clusteringModel = value;
    }

    /**
     * Gets the value of the gaussianProcessModel property.
     *
     * @return possible object is
     * {@link GaussianProcessModel }
     */
    public GaussianProcessModel getGaussianProcessModel() {
        return gaussianProcessModel;
    }

    /**
     * Sets the value of the gaussianProcessModel property.
     *
     * @param value allowed object is
     *              {@link GaussianProcessModel }
     */
    public void setGaussianProcessModel(GaussianProcessModel value) {
        this.gaussianProcessModel = value;
    }

    /**
     * Gets the value of the generalRegressionModel property.
     *
     * @return possible object is
     * {@link GeneralRegressionModel }
     */
    public GeneralRegressionModel getGeneralRegressionModel() {
        return generalRegressionModel;
    }

    /**
     * Sets the value of the generalRegressionModel property.
     *
     * @param value allowed object is
     *              {@link GeneralRegressionModel }
     */
    public void setGeneralRegressionModel(GeneralRegressionModel value) {
        this.generalRegressionModel = value;
    }

    /**
     * Gets the value of the miningModel property.
     *
     * @return possible object is
     * {@link MiningModel }
     */
    public MiningModel getMiningModel() {
        return miningModel;
    }

    /**
     * Sets the value of the miningModel property.
     *
     * @param value allowed object is
     *              {@link MiningModel }
     */
    public void setMiningModel(MiningModel value) {
        this.miningModel = value;
    }

    /**
     * Gets the value of the naiveBayesModel property.
     *
     * @return possible object is
     * {@link NaiveBayesModel }
     */
    public NaiveBayesModel getNaiveBayesModel() {
        return naiveBayesModel;
    }

    /**
     * Sets the value of the naiveBayesModel property.
     *
     * @param value allowed object is
     *              {@link NaiveBayesModel }
     */
    public void setNaiveBayesModel(NaiveBayesModel value) {
        this.naiveBayesModel = value;
    }

    /**
     * Gets the value of the nearestNeighborModel property.
     *
     * @return possible object is
     * {@link NearestNeighborModel }
     */
    public NearestNeighborModel getNearestNeighborModel() {
        return nearestNeighborModel;
    }

    /**
     * Sets the value of the nearestNeighborModel property.
     *
     * @param value allowed object is
     *              {@link NearestNeighborModel }
     */
    public void setNearestNeighborModel(NearestNeighborModel value) {
        this.nearestNeighborModel = value;
    }

    /**
     * Gets the value of the neuralNetwork property.
     *
     * @return possible object is
     * {@link NeuralNetwork }
     */
    public NeuralNetwork getNeuralNetwork() {
        return neuralNetwork;
    }

    /**
     * Sets the value of the neuralNetwork property.
     *
     * @param value allowed object is
     *              {@link NeuralNetwork }
     */
    public void setNeuralNetwork(NeuralNetwork value) {
        this.neuralNetwork = value;
    }

    /**
     * Gets the value of the regressionModel property.
     *
     * @return possible object is
     * {@link RegressionModel }
     */
    public RegressionModel getRegressionModel() {
        return regressionModel;
    }

    /**
     * Sets the value of the regressionModel property.
     *
     * @param value allowed object is
     *              {@link RegressionModel }
     */
    public void setRegressionModel(RegressionModel value) {
        this.regressionModel = value;
    }

    /**
     * Gets the value of the ruleSetModel property.
     *
     * @return possible object is
     * {@link RuleSetModel }
     */
    public RuleSetModel getRuleSetModel() {
        return ruleSetModel;
    }

    /**
     * Sets the value of the ruleSetModel property.
     *
     * @param value allowed object is
     *              {@link RuleSetModel }
     */
    public void setRuleSetModel(RuleSetModel value) {
        this.ruleSetModel = value;
    }

    /**
     * Gets the value of the sequenceModel property.
     *
     * @return possible object is
     * {@link SequenceModel }
     */
    public SequenceModel getSequenceModel() {
        return sequenceModel;
    }

    /**
     * Sets the value of the sequenceModel property.
     *
     * @param value allowed object is
     *              {@link SequenceModel }
     */
    public void setSequenceModel(SequenceModel value) {
        this.sequenceModel = value;
    }

    /**
     * Gets the value of the scorecard property.
     *
     * @return possible object is
     * {@link Scorecard }
     */
    public Scorecard getScorecard() {
        return scorecard;
    }

    /**
     * Sets the value of the scorecard property.
     *
     * @param value allowed object is
     *              {@link Scorecard }
     */
    public void setScorecard(Scorecard value) {
        this.scorecard = value;
    }

    /**
     * Gets the value of the supportVectorMachineModel property.
     *
     * @return possible object is
     * {@link SupportVectorMachineModel }
     */
    public SupportVectorMachineModel getSupportVectorMachineModel() {
        return supportVectorMachineModel;
    }

    /**
     * Sets the value of the supportVectorMachineModel property.
     *
     * @param value allowed object is
     *              {@link SupportVectorMachineModel }
     */
    public void setSupportVectorMachineModel(SupportVectorMachineModel value) {
        this.supportVectorMachineModel = value;
    }

    /**
     * Gets the value of the textModel property.
     *
     * @return possible object is
     * {@link TextModel }
     */
    public TextModel getTextModel() {
        return textModel;
    }

    /**
     * Sets the value of the textModel property.
     *
     * @param value allowed object is
     *              {@link TextModel }
     */
    public void setTextModel(TextModel value) {
        this.textModel = value;
    }

    /**
     * Gets the value of the timeSeriesModel property.
     *
     * @return possible object is
     * {@link TimeSeriesModel }
     */
    public TimeSeriesModel getTimeSeriesModel() {
        return timeSeriesModel;
    }

    /**
     * Sets the value of the timeSeriesModel property.
     *
     * @param value allowed object is
     *              {@link TimeSeriesModel }
     */
    public void setTimeSeriesModel(TimeSeriesModel value) {
        this.timeSeriesModel = value;
    }

    /**
     * Gets the value of the treeModel property.
     *
     * @return possible object is
     * {@link TreeModel }
     */
    public TreeModel getTreeModel() {
        return treeModel;
    }

    /**
     * Sets the value of the treeModel property.
     *
     * @param value allowed object is
     *              {@link TreeModel }
     */
    public void setTreeModel(TreeModel value) {
        this.treeModel = value;
    }

    /**
     * Gets the value of the meanClusterDistances property.
     *
     * @return possible object is
     * {@link MeanClusterDistances }
     */
    public MeanClusterDistances getMeanClusterDistances() {
        return meanClusterDistances;
    }

    /**
     * Sets the value of the meanClusterDistances property.
     *
     * @param value allowed object is
     *              {@link MeanClusterDistances }
     */
    public void setMeanClusterDistances(MeanClusterDistances value) {
        this.meanClusterDistances = value;
    }

    /**
     * Gets the value of the modelName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the algorithmName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlgorithmName() {
        return algorithmName;
    }

    /**
     * Sets the value of the algorithmName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlgorithmName(String value) {
        this.algorithmName = value;
    }

    /**
     * Gets the value of the functionName property.
     *
     * @return possible object is
     * {@link MININGFUNCTION }
     */
    public MININGFUNCTION getFunctionName() {
        return functionName;
    }

    /**
     * Sets the value of the functionName property.
     *
     * @param value allowed object is
     *              {@link MININGFUNCTION }
     */
    public void setFunctionName(MININGFUNCTION value) {
        this.functionName = value;
    }

    /**
     * Gets the value of the algorithmType property.
     *
     * @return possible object is
     * {@link ALGORITHMTYPE }
     */
    public ALGORITHMTYPE getAlgorithmType() {
        return algorithmType;
    }

    /**
     * Sets the value of the algorithmType property.
     *
     * @param value allowed object is
     *              {@link ALGORITHMTYPE }
     */
    public void setAlgorithmType(ALGORITHMTYPE value) {
        this.algorithmType = value;
    }

    /**
     * Gets the value of the sampleDataSize property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSampleDataSize() {
        return sampleDataSize;
    }

    /**
     * Sets the value of the sampleDataSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSampleDataSize(String value) {
        this.sampleDataSize = value;
    }

    /**
     * Gets the value of the isScorable property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsScorable() {
        if (isScorable == null) {
            return true;
        } else {
            return isScorable;
        }
    }

    /**
     * Sets the value of the isScorable property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsScorable(Boolean value) {
        this.isScorable = value;
    }
}
