//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 12:47:30 PM UTC 
//

package com.anstis.pmml.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}Decisions" minOccurs="0"/&gt;
 *           &lt;group ref="{http://www.dmg.org/PMML-4_4}EXPRESSION"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}Value" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="optype" type="{http://www.dmg.org/PMML-4_4}OPTYPE" /&gt;
 *       &lt;attribute name="dataType" use="required" type="{http://www.dmg.org/PMML-4_4}DATATYPE" /&gt;
 *       &lt;attribute name="targetField" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="feature" type="{http://www.dmg.org/PMML-4_4}RESULT-FEATURE" default="predictedValue" /&gt;
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ruleFeature" type="{http://www.dmg.org/PMML-4_4}RULE-FEATURE" default="consequent" /&gt;
 *       &lt;attribute name="algorithm" default="exclusiveRecommendation"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="recommendation"/&gt;
 *             &lt;enumeration value="exclusiveRecommendation"/&gt;
 *             &lt;enumeration value="ruleAssociation"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rank" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" default="1" /&gt;
 *       &lt;attribute name="rankBasis" default="confidence"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="confidence"/&gt;
 *             &lt;enumeration value="support"/&gt;
 *             &lt;enumeration value="lift"/&gt;
 *             &lt;enumeration value="leverage"/&gt;
 *             &lt;enumeration value="affinity"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rankOrder" default="descending"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="descending"/&gt;
 *             &lt;enumeration value="ascending"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isMultiValued" type="{http://www.w3.org/2001/XMLSchema}string" default="0" /&gt;
 *       &lt;attribute name="segmentId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isFinalResult" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "extension",
        "decisions",
        "constant",
        "fieldRef",
        "normContinuous",
        "normDiscrete",
        "discretize",
        "mapValues",
        "textIndex",
        "apply",
        "aggregate",
        "lag",
        "valueAttribute"
})
@XmlRootElement(name = "OutputField")
public class OutputField {

    @XmlElement(name = "Extension")
    protected List<Extension> extension;
    @XmlElement(name = "Decisions")
    protected Decisions decisions;
    @XmlElement(name = "Constant")
    protected Constant constant;
    @XmlElement(name = "FieldRef")
    protected FieldRef fieldRef;
    @XmlElement(name = "NormContinuous")
    protected NormContinuous normContinuous;
    @XmlElement(name = "NormDiscrete")
    protected NormDiscrete normDiscrete;
    @XmlElement(name = "Discretize")
    protected Discretize discretize;
    @XmlElement(name = "MapValues")
    protected MapValues mapValues;
    @XmlElement(name = "TextIndex")
    protected TextIndex textIndex;
    @XmlElement(name = "Apply")
    protected Apply apply;
    @XmlElement(name = "Aggregate")
    protected Aggregate aggregate;
    @XmlElement(name = "Lag")
    protected Lag lag;
    @XmlElement(name = "Value")
    protected List<Value> valueAttribute;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "optype")
    protected OPTYPE optype;
    @XmlAttribute(name = "dataType", required = true)
    protected DATATYPE dataType;
    @XmlAttribute(name = "targetField")
    protected String targetField;
    @XmlAttribute(name = "feature")
    protected RESULTFEATURE feature;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "ruleFeature")
    protected RULEFEATURE ruleFeature;
    @XmlAttribute(name = "algorithm")
    protected String algorithm;
    @XmlAttribute(name = "rank")
    protected BigInteger rank;
    @XmlAttribute(name = "rankBasis")
    protected String rankBasis;
    @XmlAttribute(name = "rankOrder")
    protected String rankOrder;
    @XmlAttribute(name = "isMultiValued")
    protected String isMultiValued;
    @XmlAttribute(name = "segmentId")
    protected String segmentId;
    @XmlAttribute(name = "isFinalResult")
    protected Boolean isFinalResult;

    /**
     * Gets the value of the extension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the decisions property.
     *
     * @return possible object is
     * {@link Decisions }
     */
    public Decisions getDecisions() {
        return decisions;
    }

    /**
     * Sets the value of the decisions property.
     *
     * @param value allowed object is
     *              {@link Decisions }
     */
    public void setDecisions(Decisions value) {
        this.decisions = value;
    }

    /**
     * Gets the value of the constant property.
     *
     * @return possible object is
     * {@link Constant }
     */
    public Constant getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     *
     * @param value allowed object is
     *              {@link Constant }
     */
    public void setConstant(Constant value) {
        this.constant = value;
    }

    /**
     * Gets the value of the fieldRef property.
     *
     * @return possible object is
     * {@link FieldRef }
     */
    public FieldRef getFieldRef() {
        return fieldRef;
    }

    /**
     * Sets the value of the fieldRef property.
     *
     * @param value allowed object is
     *              {@link FieldRef }
     */
    public void setFieldRef(FieldRef value) {
        this.fieldRef = value;
    }

    /**
     * Gets the value of the normContinuous property.
     *
     * @return possible object is
     * {@link NormContinuous }
     */
    public NormContinuous getNormContinuous() {
        return normContinuous;
    }

    /**
     * Sets the value of the normContinuous property.
     *
     * @param value allowed object is
     *              {@link NormContinuous }
     */
    public void setNormContinuous(NormContinuous value) {
        this.normContinuous = value;
    }

    /**
     * Gets the value of the normDiscrete property.
     *
     * @return possible object is
     * {@link NormDiscrete }
     */
    public NormDiscrete getNormDiscrete() {
        return normDiscrete;
    }

    /**
     * Sets the value of the normDiscrete property.
     *
     * @param value allowed object is
     *              {@link NormDiscrete }
     */
    public void setNormDiscrete(NormDiscrete value) {
        this.normDiscrete = value;
    }

    /**
     * Gets the value of the discretize property.
     *
     * @return possible object is
     * {@link Discretize }
     */
    public Discretize getDiscretize() {
        return discretize;
    }

    /**
     * Sets the value of the discretize property.
     *
     * @param value allowed object is
     *              {@link Discretize }
     */
    public void setDiscretize(Discretize value) {
        this.discretize = value;
    }

    /**
     * Gets the value of the mapValues property.
     *
     * @return possible object is
     * {@link MapValues }
     */
    public MapValues getMapValues() {
        return mapValues;
    }

    /**
     * Sets the value of the mapValues property.
     *
     * @param value allowed object is
     *              {@link MapValues }
     */
    public void setMapValues(MapValues value) {
        this.mapValues = value;
    }

    /**
     * Gets the value of the textIndex property.
     *
     * @return possible object is
     * {@link TextIndex }
     */
    public TextIndex getTextIndex() {
        return textIndex;
    }

    /**
     * Sets the value of the textIndex property.
     *
     * @param value allowed object is
     *              {@link TextIndex }
     */
    public void setTextIndex(TextIndex value) {
        this.textIndex = value;
    }

    /**
     * Gets the value of the apply property.
     *
     * @return possible object is
     * {@link Apply }
     */
    public Apply getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     *
     * @param value allowed object is
     *              {@link Apply }
     */
    public void setApply(Apply value) {
        this.apply = value;
    }

    /**
     * Gets the value of the aggregate property.
     *
     * @return possible object is
     * {@link Aggregate }
     */
    public Aggregate getAggregate() {
        return aggregate;
    }

    /**
     * Sets the value of the aggregate property.
     *
     * @param value allowed object is
     *              {@link Aggregate }
     */
    public void setAggregate(Aggregate value) {
        this.aggregate = value;
    }

    /**
     * Gets the value of the lag property.
     *
     * @return possible object is
     * {@link Lag }
     */
    public Lag getLag() {
        return lag;
    }

    /**
     * Sets the value of the lag property.
     *
     * @param value allowed object is
     *              {@link Lag }
     */
    public void setLag(Lag value) {
        this.lag = value;
    }

    /**
     * Gets the value of the valueAttribute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueAttribute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueAttribute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Value }
     */
    public List<Value> getValueAttribute() {
        if (valueAttribute == null) {
            valueAttribute = new ArrayList<Value>();
        }
        return this.valueAttribute;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the optype property.
     *
     * @return possible object is
     * {@link OPTYPE }
     */
    public OPTYPE getOptype() {
        return optype;
    }

    /**
     * Sets the value of the optype property.
     *
     * @param value allowed object is
     *              {@link OPTYPE }
     */
    public void setOptype(OPTYPE value) {
        this.optype = value;
    }

    /**
     * Gets the value of the dataType property.
     *
     * @return possible object is
     * {@link DATATYPE }
     */
    public DATATYPE getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     *
     * @param value allowed object is
     *              {@link DATATYPE }
     */
    public void setDataType(DATATYPE value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the targetField property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTargetField() {
        return targetField;
    }

    /**
     * Sets the value of the targetField property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetField(String value) {
        this.targetField = value;
    }

    /**
     * Gets the value of the feature property.
     *
     * @return possible object is
     * {@link RESULTFEATURE }
     */
    public RESULTFEATURE getFeature() {
        if (feature == null) {
            return RESULTFEATURE.PREDICTED_VALUE;
        } else {
            return feature;
        }
    }

    /**
     * Sets the value of the feature property.
     *
     * @param value allowed object is
     *              {@link RESULTFEATURE }
     */
    public void setFeature(RESULTFEATURE value) {
        this.feature = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the ruleFeature property.
     *
     * @return possible object is
     * {@link RULEFEATURE }
     */
    public RULEFEATURE getRuleFeature() {
        if (ruleFeature == null) {
            return RULEFEATURE.CONSEQUENT;
        } else {
            return ruleFeature;
        }
    }

    /**
     * Sets the value of the ruleFeature property.
     *
     * @param value allowed object is
     *              {@link RULEFEATURE }
     */
    public void setRuleFeature(RULEFEATURE value) {
        this.ruleFeature = value;
    }

    /**
     * Gets the value of the algorithm property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlgorithm() {
        if (algorithm == null) {
            return "exclusiveRecommendation";
        } else {
            return algorithm;
        }
    }

    /**
     * Sets the value of the algorithm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlgorithm(String value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the rank property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getRank() {
        if (rank == null) {
            return new BigInteger("1");
        } else {
            return rank;
        }
    }

    /**
     * Sets the value of the rank property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setRank(BigInteger value) {
        this.rank = value;
    }

    /**
     * Gets the value of the rankBasis property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRankBasis() {
        if (rankBasis == null) {
            return "confidence";
        } else {
            return rankBasis;
        }
    }

    /**
     * Sets the value of the rankBasis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRankBasis(String value) {
        this.rankBasis = value;
    }

    /**
     * Gets the value of the rankOrder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRankOrder() {
        if (rankOrder == null) {
            return "descending";
        } else {
            return rankOrder;
        }
    }

    /**
     * Sets the value of the rankOrder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRankOrder(String value) {
        this.rankOrder = value;
    }

    /**
     * Gets the value of the isMultiValued property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsMultiValued() {
        if (isMultiValued == null) {
            return "0";
        } else {
            return isMultiValued;
        }
    }

    /**
     * Sets the value of the isMultiValued property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsMultiValued(String value) {
        this.isMultiValued = value;
    }

    /**
     * Gets the value of the segmentId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSegmentId() {
        return segmentId;
    }

    /**
     * Sets the value of the segmentId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSegmentId(String value) {
        this.segmentId = value;
    }

    /**
     * Gets the value of the isFinalResult property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsFinalResult() {
        if (isFinalResult == null) {
            return true;
        } else {
            return isFinalResult;
        }
    }

    /**
     * Sets the value of the isFinalResult property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsFinalResult(Boolean value) {
        this.isFinalResult = value;
    }
}
