//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 10:52:05 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dmg.org/PMML-4_4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.anstis.pmml.model;
