//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 12:47:30 PM UTC 
//

package com.anstis.pmml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.dmg.org/PMML-4_4}CONTINUOUS-DISTRIBUTION-TYPES"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "extension",
        "anyDistribution",
        "gaussianDistribution",
        "poissonDistribution",
        "uniformDistribution"
})
@XmlRootElement(name = "TargetValueStat")
public class TargetValueStat {

    @XmlElement(name = "Extension")
    protected List<Extension> extension;
    @XmlElement(name = "AnyDistribution")
    protected AnyDistribution anyDistribution;
    @XmlElement(name = "GaussianDistribution")
    protected GaussianDistribution gaussianDistribution;
    @XmlElement(name = "PoissonDistribution")
    protected PoissonDistribution poissonDistribution;
    @XmlElement(name = "UniformDistribution")
    protected UniformDistribution uniformDistribution;
    @XmlAttribute(name = "value", required = true)
    protected String value;

    /**
     * Gets the value of the extension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the anyDistribution property.
     *
     * @return possible object is
     * {@link AnyDistribution }
     */
    public AnyDistribution getAnyDistribution() {
        return anyDistribution;
    }

    /**
     * Sets the value of the anyDistribution property.
     *
     * @param value allowed object is
     *              {@link AnyDistribution }
     */
    public void setAnyDistribution(AnyDistribution value) {
        this.anyDistribution = value;
    }

    /**
     * Gets the value of the gaussianDistribution property.
     *
     * @return possible object is
     * {@link GaussianDistribution }
     */
    public GaussianDistribution getGaussianDistribution() {
        return gaussianDistribution;
    }

    /**
     * Sets the value of the gaussianDistribution property.
     *
     * @param value allowed object is
     *              {@link GaussianDistribution }
     */
    public void setGaussianDistribution(GaussianDistribution value) {
        this.gaussianDistribution = value;
    }

    /**
     * Gets the value of the poissonDistribution property.
     *
     * @return possible object is
     * {@link PoissonDistribution }
     */
    public PoissonDistribution getPoissonDistribution() {
        return poissonDistribution;
    }

    /**
     * Sets the value of the poissonDistribution property.
     *
     * @param value allowed object is
     *              {@link PoissonDistribution }
     */
    public void setPoissonDistribution(PoissonDistribution value) {
        this.poissonDistribution = value;
    }

    /**
     * Gets the value of the uniformDistribution property.
     *
     * @return possible object is
     * {@link UniformDistribution }
     */
    public UniformDistribution getUniformDistribution() {
        return uniformDistribution;
    }

    /**
     * Sets the value of the uniformDistribution property.
     *
     * @param value allowed object is
     *              {@link UniformDistribution }
     */
    public void setUniformDistribution(UniformDistribution value) {
        this.uniformDistribution = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }
}
