//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.16 at 10:37:58 AM BST 
//


package com.anstis.pmml.model.impl.v4_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import jsinterop.annotations.JsType;
import org.treblereel.j2cl.processors.annotations.GWT3Export;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Array"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "array"
})
@XmlRootElement(name = "INT-ARRAY")
@JsType
@GWT3Export
public class INTARRAY
    implements com.anstis.pmml.model.api.INTARRAY
{

    @XmlElement(name = "Array", type = ArrayType.class)
    protected com.anstis.pmml.model.api.ArrayType array;

    /**
     * Gets the value of the array property.
     *
     * @return
     *     possible object is
     *     {@link ArrayType }
     *
     */
    public com.anstis.pmml.model.api.ArrayType getArray() {
        return array;
    }

    /**
     * Sets the value of the array property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayType }
     *     
     */
    public void setArray(com.anstis.pmml.model.api.ArrayType value) {
        this.array = value;
    }

}
