//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.03 at 09:25:28 AM BST 
//


package com.anstis.pmml.model.impl.v4_4;

import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anstis.pmml.model.impl.v4_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Array_QNAME = new QName("http://www.dmg.org/PMML-4_4", "Array");
    private final static QName _Indices_QNAME = new QName("http://www.dmg.org/PMML-4_4", "Indices");
    private final static QName _REALEntries_QNAME = new QName("http://www.dmg.org/PMML-4_4", "REAL-Entries");
    private final static QName _SpectralAnalysis_QNAME = new QName("http://www.dmg.org/PMML-4_4", "SpectralAnalysis");
    private final static QName _SeasonalTrendDecomposition_QNAME = new QName("http://www.dmg.org/PMML-4_4", "SeasonalTrendDecomposition");
    private final static QName _INTEntries_QNAME = new QName("http://www.dmg.org/PMML-4_4", "INT-Entries");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anstis.pmml.model.impl.v4_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefineFunction }
     * 
     */
    public DefineFunction createDefineFunction() {
        return new DefineFunction();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link ParameterField }
     * 
     */
    public ParameterField createParameterField() {
        return new ParameterField();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link FieldRef }
     * 
     */
    public FieldRef createFieldRef() {
        return new FieldRef();
    }

    /**
     * Create an instance of {@link NormContinuous }
     * 
     */
    public NormContinuous createNormContinuous() {
        return new NormContinuous();
    }

    /**
     * Create an instance of {@link LinearNorm }
     * 
     */
    public LinearNorm createLinearNorm() {
        return new LinearNorm();
    }

    /**
     * Create an instance of {@link NormDiscrete }
     * 
     */
    public NormDiscrete createNormDiscrete() {
        return new NormDiscrete();
    }

    /**
     * Create an instance of {@link Discretize }
     * 
     */
    public Discretize createDiscretize() {
        return new Discretize();
    }

    /**
     * Create an instance of {@link DiscretizeBin }
     * 
     */
    public DiscretizeBin createDiscretizeBin() {
        return new DiscretizeBin();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link MapValues }
     * 
     */
    public MapValues createMapValues() {
        return new MapValues();
    }

    /**
     * Create an instance of {@link FieldColumnPair }
     * 
     */
    public FieldColumnPair createFieldColumnPair() {
        return new FieldColumnPair();
    }

    /**
     * Create an instance of {@link TableLocator }
     * 
     */
    public TableLocator createTableLocator() {
        return new TableLocator();
    }

    /**
     * Create an instance of {@link InlineTable }
     * 
     */
    public InlineTable createInlineTable() {
        return new InlineTable();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link TextIndex }
     * 
     */
    public TextIndex createTextIndex() {
        return new TextIndex();
    }

    /**
     * Create an instance of {@link TextIndexNormalization }
     * 
     */
    public TextIndexNormalization createTextIndexNormalization() {
        return new TextIndexNormalization();
    }

    /**
     * Create an instance of {@link Apply }
     * 
     */
    public Apply createApply() {
        return new Apply();
    }

    /**
     * Create an instance of {@link Aggregate }
     * 
     */
    public Aggregate createAggregate() {
        return new Aggregate();
    }

    /**
     * Create an instance of {@link Lag }
     * 
     */
    public Lag createLag() {
        return new Lag();
    }

    /**
     * Create an instance of {@link BlockIndicator }
     * 
     */
    public BlockIndicator createBlockIndicator() {
        return new BlockIndicator();
    }

    /**
     * Create an instance of {@link MiningModel }
     * 
     */
    public MiningModel createMiningModel() {
        return new MiningModel();
    }

    /**
     * Create an instance of {@link MiningSchema }
     * 
     */
    public MiningSchema createMiningSchema() {
        return new MiningSchema();
    }

    /**
     * Create an instance of {@link MiningField }
     * 
     */
    public MiningField createMiningField() {
        return new MiningField();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link OutputField }
     * 
     */
    public OutputField createOutputField() {
        return new OutputField();
    }

    /**
     * Create an instance of {@link Decisions }
     * 
     */
    public Decisions createDecisions() {
        return new Decisions();
    }

    /**
     * Create an instance of {@link Decision }
     * 
     */
    public Decision createDecision() {
        return new Decision();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link ModelStats }
     * 
     */
    public ModelStats createModelStats() {
        return new ModelStats();
    }

    /**
     * Create an instance of {@link UnivariateStats }
     * 
     */
    public UnivariateStats createUnivariateStats() {
        return new UnivariateStats();
    }

    /**
     * Create an instance of {@link Counts }
     * 
     */
    public Counts createCounts() {
        return new Counts();
    }

    /**
     * Create an instance of {@link NumericInfo }
     * 
     */
    public NumericInfo createNumericInfo() {
        return new NumericInfo();
    }

    /**
     * Create an instance of {@link Quantile }
     * 
     */
    public Quantile createQuantile() {
        return new Quantile();
    }

    /**
     * Create an instance of {@link DiscrStats }
     * 
     */
    public DiscrStats createDiscrStats() {
        return new DiscrStats();
    }

    /**
     * Create an instance of {@link ArrayType }
     * 
     */
    public ArrayType createArrayType() {
        return new ArrayType();
    }

    /**
     * Create an instance of {@link ContStats }
     * 
     */
    public ContStats createContStats() {
        return new ContStats();
    }

    /**
     * Create an instance of {@link NUMARRAY }
     * 
     */
    public NUMARRAY createNUMARRAY() {
        return new NUMARRAY();
    }

    /**
     * Create an instance of {@link Anova }
     * 
     */
    public Anova createAnova() {
        return new Anova();
    }

    /**
     * Create an instance of {@link AnovaRow }
     * 
     */
    public AnovaRow createAnovaRow() {
        return new AnovaRow();
    }

    /**
     * Create an instance of {@link MultivariateStats }
     * 
     */
    public MultivariateStats createMultivariateStats() {
        return new MultivariateStats();
    }

    /**
     * Create an instance of {@link MultivariateStat }
     * 
     */
    public MultivariateStat createMultivariateStat() {
        return new MultivariateStat();
    }

    /**
     * Create an instance of {@link ModelExplanation }
     * 
     */
    public ModelExplanation createModelExplanation() {
        return new ModelExplanation();
    }

    /**
     * Create an instance of {@link PredictiveModelQuality }
     * 
     */
    public PredictiveModelQuality createPredictiveModelQuality() {
        return new PredictiveModelQuality();
    }

    /**
     * Create an instance of {@link ConfusionMatrix }
     * 
     */
    public ConfusionMatrix createConfusionMatrix() {
        return new ConfusionMatrix();
    }

    /**
     * Create an instance of {@link ClassLabels }
     * 
     */
    public ClassLabels createClassLabels() {
        return new ClassLabels();
    }

    /**
     * Create an instance of {@link STRINGARRAY }
     * 
     */
    public STRINGARRAY createSTRINGARRAY() {
        return new STRINGARRAY();
    }

    /**
     * Create an instance of {@link Matrix }
     * 
     */
    public Matrix createMatrix() {
        return new Matrix();
    }

    /**
     * Create an instance of {@link MatCell }
     * 
     */
    public MatCell createMatCell() {
        return new MatCell();
    }

    /**
     * Create an instance of {@link LiftData }
     * 
     */
    public LiftData createLiftData() {
        return new LiftData();
    }

    /**
     * Create an instance of {@link ModelLiftGraph }
     * 
     */
    public ModelLiftGraph createModelLiftGraph() {
        return new ModelLiftGraph();
    }

    /**
     * Create an instance of {@link LiftGraph }
     * 
     */
    public LiftGraph createLiftGraph() {
        return new LiftGraph();
    }

    /**
     * Create an instance of {@link XCoordinates }
     * 
     */
    public XCoordinates createXCoordinates() {
        return new XCoordinates();
    }

    /**
     * Create an instance of {@link YCoordinates }
     * 
     */
    public YCoordinates createYCoordinates() {
        return new YCoordinates();
    }

    /**
     * Create an instance of {@link BoundaryValues }
     * 
     */
    public BoundaryValues createBoundaryValues() {
        return new BoundaryValues();
    }

    /**
     * Create an instance of {@link BoundaryValueMeans }
     * 
     */
    public BoundaryValueMeans createBoundaryValueMeans() {
        return new BoundaryValueMeans();
    }

    /**
     * Create an instance of {@link OptimumLiftGraph }
     * 
     */
    public OptimumLiftGraph createOptimumLiftGraph() {
        return new OptimumLiftGraph();
    }

    /**
     * Create an instance of {@link RandomLiftGraph }
     * 
     */
    public RandomLiftGraph createRandomLiftGraph() {
        return new RandomLiftGraph();
    }

    /**
     * Create an instance of {@link ROC }
     * 
     */
    public ROC createROC() {
        return new ROC();
    }

    /**
     * Create an instance of {@link ROCGraph }
     * 
     */
    public ROCGraph createROCGraph() {
        return new ROCGraph();
    }

    /**
     * Create an instance of {@link ClusteringModelQuality }
     * 
     */
    public ClusteringModelQuality createClusteringModelQuality() {
        return new ClusteringModelQuality();
    }

    /**
     * Create an instance of {@link Correlations }
     * 
     */
    public Correlations createCorrelations() {
        return new Correlations();
    }

    /**
     * Create an instance of {@link CorrelationFields }
     * 
     */
    public CorrelationFields createCorrelationFields() {
        return new CorrelationFields();
    }

    /**
     * Create an instance of {@link CorrelationValues }
     * 
     */
    public CorrelationValues createCorrelationValues() {
        return new CorrelationValues();
    }

    /**
     * Create an instance of {@link CorrelationMethods }
     * 
     */
    public CorrelationMethods createCorrelationMethods() {
        return new CorrelationMethods();
    }

    /**
     * Create an instance of {@link Targets }
     * 
     */
    public Targets createTargets() {
        return new Targets();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link TargetValue }
     * 
     */
    public TargetValue createTargetValue() {
        return new TargetValue();
    }

    /**
     * Create an instance of {@link Partition }
     * 
     */
    public Partition createPartition() {
        return new Partition();
    }

    /**
     * Create an instance of {@link PartitionFieldStats }
     * 
     */
    public PartitionFieldStats createPartitionFieldStats() {
        return new PartitionFieldStats();
    }

    /**
     * Create an instance of {@link LocalTransformations }
     * 
     */
    public LocalTransformations createLocalTransformations() {
        return new LocalTransformations();
    }

    /**
     * Create an instance of {@link DerivedField }
     * 
     */
    public DerivedField createDerivedField() {
        return new DerivedField();
    }

    /**
     * Create an instance of {@link Regression }
     * 
     */
    public Regression createRegression() {
        return new Regression();
    }

    /**
     * Create an instance of {@link ResultField }
     * 
     */
    public ResultField createResultField() {
        return new ResultField();
    }

    /**
     * Create an instance of {@link RegressionTable }
     * 
     */
    public RegressionTable createRegressionTable() {
        return new RegressionTable();
    }

    /**
     * Create an instance of {@link NumericPredictor }
     * 
     */
    public NumericPredictor createNumericPredictor() {
        return new NumericPredictor();
    }

    /**
     * Create an instance of {@link CategoricalPredictor }
     * 
     */
    public CategoricalPredictor createCategoricalPredictor() {
        return new CategoricalPredictor();
    }

    /**
     * Create an instance of {@link PredictorTerm }
     * 
     */
    public PredictorTerm createPredictorTerm() {
        return new PredictorTerm();
    }

    /**
     * Create an instance of {@link DecisionTree }
     * 
     */
    public DecisionTree createDecisionTree() {
        return new DecisionTree();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link SimplePredicate }
     * 
     */
    public SimplePredicate createSimplePredicate() {
        return new SimplePredicate();
    }

    /**
     * Create an instance of {@link CompoundPredicate }
     * 
     */
    public CompoundPredicate createCompoundPredicate() {
        return new CompoundPredicate();
    }

    /**
     * Create an instance of {@link SimpleSetPredicate }
     * 
     */
    public SimpleSetPredicate createSimpleSetPredicate() {
        return new SimpleSetPredicate();
    }

    /**
     * Create an instance of {@link True }
     * 
     */
    public True createTrue() {
        return new True();
    }

    /**
     * Create an instance of {@link False }
     * 
     */
    public False createFalse() {
        return new False();
    }

    /**
     * Create an instance of {@link ScoreDistribution }
     * 
     */
    public ScoreDistribution createScoreDistribution() {
        return new ScoreDistribution();
    }

    /**
     * Create an instance of {@link Segmentation }
     * 
     */
    public Segmentation createSegmentation() {
        return new Segmentation();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link AnomalyDetectionModel }
     * 
     */
    public AnomalyDetectionModel createAnomalyDetectionModel() {
        return new AnomalyDetectionModel();
    }

    /**
     * Create an instance of {@link ModelVerification }
     * 
     */
    public ModelVerification createModelVerification() {
        return new ModelVerification();
    }

    /**
     * Create an instance of {@link VerificationFields }
     * 
     */
    public VerificationFields createVerificationFields() {
        return new VerificationFields();
    }

    /**
     * Create an instance of {@link VerificationField }
     * 
     */
    public VerificationField createVerificationField() {
        return new VerificationField();
    }

    /**
     * Create an instance of {@link AssociationModel }
     * 
     */
    public AssociationModel createAssociationModel() {
        return new AssociationModel();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Itemset }
     * 
     */
    public Itemset createItemset() {
        return new Itemset();
    }

    /**
     * Create an instance of {@link ItemRef }
     * 
     */
    public ItemRef createItemRef() {
        return new ItemRef();
    }

    /**
     * Create an instance of {@link AssociationRule }
     * 
     */
    public AssociationRule createAssociationRule() {
        return new AssociationRule();
    }

    /**
     * Create an instance of {@link BayesianNetworkModel }
     * 
     */
    public BayesianNetworkModel createBayesianNetworkModel() {
        return new BayesianNetworkModel();
    }

    /**
     * Create an instance of {@link BayesianNetworkNodes }
     * 
     */
    public BayesianNetworkNodes createBayesianNetworkNodes() {
        return new BayesianNetworkNodes();
    }

    /**
     * Create an instance of {@link DiscreteNode }
     * 
     */
    public DiscreteNode createDiscreteNode() {
        return new DiscreteNode();
    }

    /**
     * Create an instance of {@link DiscreteConditionalProbability }
     * 
     */
    public DiscreteConditionalProbability createDiscreteConditionalProbability() {
        return new DiscreteConditionalProbability();
    }

    /**
     * Create an instance of {@link ParentValue }
     * 
     */
    public ParentValue createParentValue() {
        return new ParentValue();
    }

    /**
     * Create an instance of {@link ValueProbability }
     * 
     */
    public ValueProbability createValueProbability() {
        return new ValueProbability();
    }

    /**
     * Create an instance of {@link ContinuousNode }
     * 
     */
    public ContinuousNode createContinuousNode() {
        return new ContinuousNode();
    }

    /**
     * Create an instance of {@link ContinuousConditionalProbability }
     * 
     */
    public ContinuousConditionalProbability createContinuousConditionalProbability() {
        return new ContinuousConditionalProbability();
    }

    /**
     * Create an instance of {@link ContinuousDistribution }
     * 
     */
    public ContinuousDistribution createContinuousDistribution() {
        return new ContinuousDistribution();
    }

    /**
     * Create an instance of {@link TriangularDistributionForBN }
     * 
     */
    public TriangularDistributionForBN createTriangularDistributionForBN() {
        return new TriangularDistributionForBN();
    }

    /**
     * Create an instance of {@link Mean }
     * 
     */
    public Mean createMean() {
        return new Mean();
    }

    /**
     * Create an instance of {@link Lower }
     * 
     */
    public Lower createLower() {
        return new Lower();
    }

    /**
     * Create an instance of {@link Upper }
     * 
     */
    public Upper createUpper() {
        return new Upper();
    }

    /**
     * Create an instance of {@link NormalDistributionForBN }
     * 
     */
    public NormalDistributionForBN createNormalDistributionForBN() {
        return new NormalDistributionForBN();
    }

    /**
     * Create an instance of {@link Variance }
     * 
     */
    public Variance createVariance() {
        return new Variance();
    }

    /**
     * Create an instance of {@link LognormalDistributionForBN }
     * 
     */
    public LognormalDistributionForBN createLognormalDistributionForBN() {
        return new LognormalDistributionForBN();
    }

    /**
     * Create an instance of {@link UniformDistributionForBN }
     * 
     */
    public UniformDistributionForBN createUniformDistributionForBN() {
        return new UniformDistributionForBN();
    }

    /**
     * Create an instance of {@link BaselineModel }
     * 
     */
    public BaselineModel createBaselineModel() {
        return new BaselineModel();
    }

    /**
     * Create an instance of {@link TestDistributions }
     * 
     */
    public TestDistributions createTestDistributions() {
        return new TestDistributions();
    }

    /**
     * Create an instance of {@link Baseline }
     * 
     */
    public Baseline createBaseline() {
        return new Baseline();
    }

    /**
     * Create an instance of {@link AnyDistribution }
     * 
     */
    public AnyDistribution createAnyDistribution() {
        return new AnyDistribution();
    }

    /**
     * Create an instance of {@link GaussianDistribution }
     * 
     */
    public GaussianDistribution createGaussianDistribution() {
        return new GaussianDistribution();
    }

    /**
     * Create an instance of {@link PoissonDistribution }
     * 
     */
    public PoissonDistribution createPoissonDistribution() {
        return new PoissonDistribution();
    }

    /**
     * Create an instance of {@link UniformDistribution }
     * 
     */
    public UniformDistribution createUniformDistribution() {
        return new UniformDistribution();
    }

    /**
     * Create an instance of {@link CountTable }
     * 
     */
    public CountTable createCountTable() {
        return new CountTable();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link FieldValueCount }
     * 
     */
    public FieldValueCount createFieldValueCount() {
        return new FieldValueCount();
    }

    /**
     * Create an instance of {@link NormalizedCountTable }
     * 
     */
    public NormalizedCountTable createNormalizedCountTable() {
        return new NormalizedCountTable();
    }

    /**
     * Create an instance of {@link Alternate }
     * 
     */
    public Alternate createAlternate() {
        return new Alternate();
    }

    /**
     * Create an instance of {@link ClusteringModel }
     * 
     */
    public ClusteringModel createClusteringModel() {
        return new ClusteringModel();
    }

    /**
     * Create an instance of {@link ComparisonMeasure }
     * 
     */
    public ComparisonMeasure createComparisonMeasure() {
        return new ComparisonMeasure();
    }

    /**
     * Create an instance of {@link Euclidean }
     * 
     */
    public Euclidean createEuclidean() {
        return new Euclidean();
    }

    /**
     * Create an instance of {@link SquaredEuclidean }
     * 
     */
    public SquaredEuclidean createSquaredEuclidean() {
        return new SquaredEuclidean();
    }

    /**
     * Create an instance of {@link Chebychev }
     * 
     */
    public Chebychev createChebychev() {
        return new Chebychev();
    }

    /**
     * Create an instance of {@link CityBlock }
     * 
     */
    public CityBlock createCityBlock() {
        return new CityBlock();
    }

    /**
     * Create an instance of {@link Minkowski }
     * 
     */
    public Minkowski createMinkowski() {
        return new Minkowski();
    }

    /**
     * Create an instance of {@link SimpleMatching }
     * 
     */
    public SimpleMatching createSimpleMatching() {
        return new SimpleMatching();
    }

    /**
     * Create an instance of {@link Jaccard }
     * 
     */
    public Jaccard createJaccard() {
        return new Jaccard();
    }

    /**
     * Create an instance of {@link Tanimoto }
     * 
     */
    public Tanimoto createTanimoto() {
        return new Tanimoto();
    }

    /**
     * Create an instance of {@link BinarySimilarity }
     * 
     */
    public BinarySimilarity createBinarySimilarity() {
        return new BinarySimilarity();
    }

    /**
     * Create an instance of {@link ClusteringField }
     * 
     */
    public ClusteringField createClusteringField() {
        return new ClusteringField();
    }

    /**
     * Create an instance of {@link Comparisons }
     * 
     */
    public Comparisons createComparisons() {
        return new Comparisons();
    }

    /**
     * Create an instance of {@link MissingValueWeights }
     * 
     */
    public MissingValueWeights createMissingValueWeights() {
        return new MissingValueWeights();
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link KohonenMap }
     * 
     */
    public KohonenMap createKohonenMap() {
        return new KohonenMap();
    }

    /**
     * Create an instance of {@link Covariances }
     * 
     */
    public Covariances createCovariances() {
        return new Covariances();
    }

    /**
     * Create an instance of {@link GaussianProcessModel }
     * 
     */
    public GaussianProcessModel createGaussianProcessModel() {
        return new GaussianProcessModel();
    }

    /**
     * Create an instance of {@link RadialBasisKernel }
     * 
     */
    public RadialBasisKernel createRadialBasisKernel() {
        return new RadialBasisKernel();
    }

    /**
     * Create an instance of {@link ARDSquaredExponentialKernel }
     * 
     */
    public ARDSquaredExponentialKernel createARDSquaredExponentialKernel() {
        return new ARDSquaredExponentialKernel();
    }

    /**
     * Create an instance of {@link Lambda }
     * 
     */
    public Lambda createLambda() {
        return new Lambda();
    }

    /**
     * Create an instance of {@link REALARRAY }
     * 
     */
    public REALARRAY createREALARRAY() {
        return new REALARRAY();
    }

    /**
     * Create an instance of {@link AbsoluteExponentialKernel }
     * 
     */
    public AbsoluteExponentialKernel createAbsoluteExponentialKernel() {
        return new AbsoluteExponentialKernel();
    }

    /**
     * Create an instance of {@link GeneralizedExponentialKernel }
     * 
     */
    public GeneralizedExponentialKernel createGeneralizedExponentialKernel() {
        return new GeneralizedExponentialKernel();
    }

    /**
     * Create an instance of {@link TrainingInstances }
     * 
     */
    public TrainingInstances createTrainingInstances() {
        return new TrainingInstances();
    }

    /**
     * Create an instance of {@link InstanceFields }
     * 
     */
    public InstanceFields createInstanceFields() {
        return new InstanceFields();
    }

    /**
     * Create an instance of {@link InstanceField }
     * 
     */
    public InstanceField createInstanceField() {
        return new InstanceField();
    }

    /**
     * Create an instance of {@link GeneralRegressionModel }
     * 
     */
    public GeneralRegressionModel createGeneralRegressionModel() {
        return new GeneralRegressionModel();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link FactorList }
     * 
     */
    public FactorList createFactorList() {
        return new FactorList();
    }

    /**
     * Create an instance of {@link Predictor }
     * 
     */
    public Predictor createPredictor() {
        return new Predictor();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link CovariateList }
     * 
     */
    public CovariateList createCovariateList() {
        return new CovariateList();
    }

    /**
     * Create an instance of {@link PPMatrix }
     * 
     */
    public PPMatrix createPPMatrix() {
        return new PPMatrix();
    }

    /**
     * Create an instance of {@link PPCell }
     * 
     */
    public PPCell createPPCell() {
        return new PPCell();
    }

    /**
     * Create an instance of {@link PCovMatrix }
     * 
     */
    public PCovMatrix createPCovMatrix() {
        return new PCovMatrix();
    }

    /**
     * Create an instance of {@link PCovCell }
     * 
     */
    public PCovCell createPCovCell() {
        return new PCovCell();
    }

    /**
     * Create an instance of {@link ParamMatrix }
     * 
     */
    public ParamMatrix createParamMatrix() {
        return new ParamMatrix();
    }

    /**
     * Create an instance of {@link PCell }
     * 
     */
    public PCell createPCell() {
        return new PCell();
    }

    /**
     * Create an instance of {@link EventValues }
     * 
     */
    public EventValues createEventValues() {
        return new EventValues();
    }

    /**
     * Create an instance of {@link BaseCumHazardTables }
     * 
     */
    public BaseCumHazardTables createBaseCumHazardTables() {
        return new BaseCumHazardTables();
    }

    /**
     * Create an instance of {@link BaselineStratum }
     * 
     */
    public BaselineStratum createBaselineStratum() {
        return new BaselineStratum();
    }

    /**
     * Create an instance of {@link BaselineCell }
     * 
     */
    public BaselineCell createBaselineCell() {
        return new BaselineCell();
    }

    /**
     * Create an instance of {@link NaiveBayesModel }
     * 
     */
    public NaiveBayesModel createNaiveBayesModel() {
        return new NaiveBayesModel();
    }

    /**
     * Create an instance of {@link BayesInputs }
     * 
     */
    public BayesInputs createBayesInputs() {
        return new BayesInputs();
    }

    /**
     * Create an instance of {@link BayesInput }
     * 
     */
    public BayesInput createBayesInput() {
        return new BayesInput();
    }

    /**
     * Create an instance of {@link TargetValueStats }
     * 
     */
    public TargetValueStats createTargetValueStats() {
        return new TargetValueStats();
    }

    /**
     * Create an instance of {@link TargetValueStat }
     * 
     */
    public TargetValueStat createTargetValueStat() {
        return new TargetValueStat();
    }

    /**
     * Create an instance of {@link PairCounts }
     * 
     */
    public PairCounts createPairCounts() {
        return new PairCounts();
    }

    /**
     * Create an instance of {@link TargetValueCounts }
     * 
     */
    public TargetValueCounts createTargetValueCounts() {
        return new TargetValueCounts();
    }

    /**
     * Create an instance of {@link TargetValueCount }
     * 
     */
    public TargetValueCount createTargetValueCount() {
        return new TargetValueCount();
    }

    /**
     * Create an instance of {@link BayesOutput }
     * 
     */
    public BayesOutput createBayesOutput() {
        return new BayesOutput();
    }

    /**
     * Create an instance of {@link NearestNeighborModel }
     * 
     */
    public NearestNeighborModel createNearestNeighborModel() {
        return new NearestNeighborModel();
    }

    /**
     * Create an instance of {@link KNNInputs }
     * 
     */
    public KNNInputs createKNNInputs() {
        return new KNNInputs();
    }

    /**
     * Create an instance of {@link KNNInput }
     * 
     */
    public KNNInput createKNNInput() {
        return new KNNInput();
    }

    /**
     * Create an instance of {@link NeuralNetwork }
     * 
     */
    public NeuralNetwork createNeuralNetwork() {
        return new NeuralNetwork();
    }

    /**
     * Create an instance of {@link NeuralInputs }
     * 
     */
    public NeuralInputs createNeuralInputs() {
        return new NeuralInputs();
    }

    /**
     * Create an instance of {@link NeuralInput }
     * 
     */
    public NeuralInput createNeuralInput() {
        return new NeuralInput();
    }

    /**
     * Create an instance of {@link NeuralLayer }
     * 
     */
    public NeuralLayer createNeuralLayer() {
        return new NeuralLayer();
    }

    /**
     * Create an instance of {@link Neuron }
     * 
     */
    public Neuron createNeuron() {
        return new Neuron();
    }

    /**
     * Create an instance of {@link Con }
     * 
     */
    public Con createCon() {
        return new Con();
    }

    /**
     * Create an instance of {@link NeuralOutputs }
     * 
     */
    public NeuralOutputs createNeuralOutputs() {
        return new NeuralOutputs();
    }

    /**
     * Create an instance of {@link NeuralOutput }
     * 
     */
    public NeuralOutput createNeuralOutput() {
        return new NeuralOutput();
    }

    /**
     * Create an instance of {@link RegressionModel }
     * 
     */
    public RegressionModel createRegressionModel() {
        return new RegressionModel();
    }

    /**
     * Create an instance of {@link RuleSetModel }
     * 
     */
    public RuleSetModel createRuleSetModel() {
        return new RuleSetModel();
    }

    /**
     * Create an instance of {@link RuleSet }
     * 
     */
    public RuleSet createRuleSet() {
        return new RuleSet();
    }

    /**
     * Create an instance of {@link RuleSelectionMethod }
     * 
     */
    public RuleSelectionMethod createRuleSelectionMethod() {
        return new RuleSelectionMethod();
    }

    /**
     * Create an instance of {@link SimpleRule }
     * 
     */
    public SimpleRule createSimpleRule() {
        return new SimpleRule();
    }

    /**
     * Create an instance of {@link CompoundRule }
     * 
     */
    public CompoundRule createCompoundRule() {
        return new CompoundRule();
    }

    /**
     * Create an instance of {@link SequenceModel }
     * 
     */
    public SequenceModel createSequenceModel() {
        return new SequenceModel();
    }

    /**
     * Create an instance of {@link Constraints }
     * 
     */
    public Constraints createConstraints() {
        return new Constraints();
    }

    /**
     * Create an instance of {@link SetPredicate }
     * 
     */
    public SetPredicate createSetPredicate() {
        return new SetPredicate();
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link SetReference }
     * 
     */
    public SetReference createSetReference() {
        return new SetReference();
    }

    /**
     * Create an instance of {@link Delimiter }
     * 
     */
    public Delimiter createDelimiter() {
        return new Delimiter();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link SequenceRule }
     * 
     */
    public SequenceRule createSequenceRule() {
        return new SequenceRule();
    }

    /**
     * Create an instance of {@link AntecedentSequence }
     * 
     */
    public AntecedentSequence createAntecedentSequence() {
        return new AntecedentSequence();
    }

    /**
     * Create an instance of {@link SequenceReference }
     * 
     */
    public SequenceReference createSequenceReference() {
        return new SequenceReference();
    }

    /**
     * Create an instance of {@link ConsequentSequence }
     * 
     */
    public ConsequentSequence createConsequentSequence() {
        return new ConsequentSequence();
    }

    /**
     * Create an instance of {@link Scorecard }
     * 
     */
    public Scorecard createScorecard() {
        return new Scorecard();
    }

    /**
     * Create an instance of {@link Characteristics }
     * 
     */
    public Characteristics createCharacteristics() {
        return new Characteristics();
    }

    /**
     * Create an instance of {@link Characteristic }
     * 
     */
    public Characteristic createCharacteristic() {
        return new Characteristic();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link ComplexPartialScore }
     * 
     */
    public ComplexPartialScore createComplexPartialScore() {
        return new ComplexPartialScore();
    }

    /**
     * Create an instance of {@link SupportVectorMachineModel }
     * 
     */
    public SupportVectorMachineModel createSupportVectorMachineModel() {
        return new SupportVectorMachineModel();
    }

    /**
     * Create an instance of {@link LinearKernelType }
     * 
     */
    public LinearKernelType createLinearKernelType() {
        return new LinearKernelType();
    }

    /**
     * Create an instance of {@link PolynomialKernelType }
     * 
     */
    public PolynomialKernelType createPolynomialKernelType() {
        return new PolynomialKernelType();
    }

    /**
     * Create an instance of {@link RadialBasisKernelType }
     * 
     */
    public RadialBasisKernelType createRadialBasisKernelType() {
        return new RadialBasisKernelType();
    }

    /**
     * Create an instance of {@link SigmoidKernelType }
     * 
     */
    public SigmoidKernelType createSigmoidKernelType() {
        return new SigmoidKernelType();
    }

    /**
     * Create an instance of {@link VectorDictionary }
     * 
     */
    public VectorDictionary createVectorDictionary() {
        return new VectorDictionary();
    }

    /**
     * Create an instance of {@link VectorFields }
     * 
     */
    public VectorFields createVectorFields() {
        return new VectorFields();
    }

    /**
     * Create an instance of {@link VectorInstance }
     * 
     */
    public VectorInstance createVectorInstance() {
        return new VectorInstance();
    }

    /**
     * Create an instance of {@link REALSparseArray }
     * 
     */
    public REALSparseArray createREALSparseArray() {
        return new REALSparseArray();
    }

    /**
     * Create an instance of {@link SupportVectorMachine }
     * 
     */
    public SupportVectorMachine createSupportVectorMachine() {
        return new SupportVectorMachine();
    }

    /**
     * Create an instance of {@link SupportVectors }
     * 
     */
    public SupportVectors createSupportVectors() {
        return new SupportVectors();
    }

    /**
     * Create an instance of {@link SupportVector }
     * 
     */
    public SupportVector createSupportVector() {
        return new SupportVector();
    }

    /**
     * Create an instance of {@link Coefficients }
     * 
     */
    public Coefficients createCoefficients() {
        return new Coefficients();
    }

    /**
     * Create an instance of {@link Coefficient }
     * 
     */
    public Coefficient createCoefficient() {
        return new Coefficient();
    }

    /**
     * Create an instance of {@link TextModel }
     * 
     */
    public TextModel createTextModel() {
        return new TextModel();
    }

    /**
     * Create an instance of {@link TextDictionary }
     * 
     */
    public TextDictionary createTextDictionary() {
        return new TextDictionary();
    }

    /**
     * Create an instance of {@link Taxonomy }
     * 
     */
    public Taxonomy createTaxonomy() {
        return new Taxonomy();
    }

    /**
     * Create an instance of {@link ChildParent }
     * 
     */
    public ChildParent createChildParent() {
        return new ChildParent();
    }

    /**
     * Create an instance of {@link TextCorpus }
     * 
     */
    public TextCorpus createTextCorpus() {
        return new TextCorpus();
    }

    /**
     * Create an instance of {@link TextDocument }
     * 
     */
    public TextDocument createTextDocument() {
        return new TextDocument();
    }

    /**
     * Create an instance of {@link DocumentTermMatrix }
     * 
     */
    public DocumentTermMatrix createDocumentTermMatrix() {
        return new DocumentTermMatrix();
    }

    /**
     * Create an instance of {@link TextModelNormalization }
     * 
     */
    public TextModelNormalization createTextModelNormalization() {
        return new TextModelNormalization();
    }

    /**
     * Create an instance of {@link TextModelSimiliarity }
     * 
     */
    public TextModelSimiliarity createTextModelSimiliarity() {
        return new TextModelSimiliarity();
    }

    /**
     * Create an instance of {@link TimeSeriesModel }
     * 
     */
    public TimeSeriesModel createTimeSeriesModel() {
        return new TimeSeriesModel();
    }

    /**
     * Create an instance of {@link TimeSeries }
     * 
     */
    public TimeSeries createTimeSeries() {
        return new TimeSeries();
    }

    /**
     * Create an instance of {@link TimeAnchor }
     * 
     */
    public TimeAnchor createTimeAnchor() {
        return new TimeAnchor();
    }

    /**
     * Create an instance of {@link TimeCycle }
     * 
     */
    public TimeCycle createTimeCycle() {
        return new TimeCycle();
    }

    /**
     * Create an instance of {@link INTARRAY }
     * 
     */
    public INTARRAY createINTARRAY() {
        return new INTARRAY();
    }

    /**
     * Create an instance of {@link TimeException }
     * 
     */
    public TimeException createTimeException() {
        return new TimeException();
    }

    /**
     * Create an instance of {@link TimeValue }
     * 
     */
    public TimeValue createTimeValue() {
        return new TimeValue();
    }

    /**
     * Create an instance of {@link Timestamp }
     * 
     */
    public Timestamp createTimestamp() {
        return new Timestamp();
    }

    /**
     * Create an instance of {@link ARIMA }
     * 
     */
    public ARIMA createARIMA() {
        return new ARIMA();
    }

    /**
     * Create an instance of {@link NonseasonalComponent }
     * 
     */
    public NonseasonalComponent createNonseasonalComponent() {
        return new NonseasonalComponent();
    }

    /**
     * Create an instance of {@link AR }
     * 
     */
    public AR createAR() {
        return new AR();
    }

    /**
     * Create an instance of {@link MA }
     * 
     */
    public MA createMA() {
        return new MA();
    }

    /**
     * Create an instance of {@link MACoefficients }
     * 
     */
    public MACoefficients createMACoefficients() {
        return new MACoefficients();
    }

    /**
     * Create an instance of {@link Residuals }
     * 
     */
    public Residuals createResiduals() {
        return new Residuals();
    }

    /**
     * Create an instance of {@link SeasonalComponent }
     * 
     */
    public SeasonalComponent createSeasonalComponent() {
        return new SeasonalComponent();
    }

    /**
     * Create an instance of {@link DynamicRegressor }
     * 
     */
    public DynamicRegressor createDynamicRegressor() {
        return new DynamicRegressor();
    }

    /**
     * Create an instance of {@link Numerator }
     * 
     */
    public Numerator createNumerator() {
        return new Numerator();
    }

    /**
     * Create an instance of {@link NonseasonalFactor }
     * 
     */
    public NonseasonalFactor createNonseasonalFactor() {
        return new NonseasonalFactor();
    }

    /**
     * Create an instance of {@link SeasonalFactor }
     * 
     */
    public SeasonalFactor createSeasonalFactor() {
        return new SeasonalFactor();
    }

    /**
     * Create an instance of {@link Denominator }
     * 
     */
    public Denominator createDenominator() {
        return new Denominator();
    }

    /**
     * Create an instance of {@link RegressorValues }
     * 
     */
    public RegressorValues createRegressorValues() {
        return new RegressorValues();
    }

    /**
     * Create an instance of {@link TrendCoefficients }
     * 
     */
    public TrendCoefficients createTrendCoefficients() {
        return new TrendCoefficients();
    }

    /**
     * Create an instance of {@link TransferFunctionValues }
     * 
     */
    public TransferFunctionValues createTransferFunctionValues() {
        return new TransferFunctionValues();
    }

    /**
     * Create an instance of {@link MaximumLikelihoodStat }
     * 
     */
    public MaximumLikelihoodStat createMaximumLikelihoodStat() {
        return new MaximumLikelihoodStat();
    }

    /**
     * Create an instance of {@link KalmanState }
     * 
     */
    public KalmanState createKalmanState() {
        return new KalmanState();
    }

    /**
     * Create an instance of {@link FinalOmega }
     * 
     */
    public FinalOmega createFinalOmega() {
        return new FinalOmega();
    }

    /**
     * Create an instance of {@link FinalStateVector }
     * 
     */
    public FinalStateVector createFinalStateVector() {
        return new FinalStateVector();
    }

    /**
     * Create an instance of {@link HVector }
     * 
     */
    public HVector createHVector() {
        return new HVector();
    }

    /**
     * Create an instance of {@link ThetaRecursionState }
     * 
     */
    public ThetaRecursionState createThetaRecursionState() {
        return new ThetaRecursionState();
    }

    /**
     * Create an instance of {@link FinalNoise }
     * 
     */
    public FinalNoise createFinalNoise() {
        return new FinalNoise();
    }

    /**
     * Create an instance of {@link FinalPredictedNoise }
     * 
     */
    public FinalPredictedNoise createFinalPredictedNoise() {
        return new FinalPredictedNoise();
    }

    /**
     * Create an instance of {@link FinalTheta }
     * 
     */
    public FinalTheta createFinalTheta() {
        return new FinalTheta();
    }

    /**
     * Create an instance of {@link Theta }
     * 
     */
    public Theta createTheta() {
        return new Theta();
    }

    /**
     * Create an instance of {@link FinalNu }
     * 
     */
    public FinalNu createFinalNu() {
        return new FinalNu();
    }

    /**
     * Create an instance of {@link OutlierEffect }
     * 
     */
    public OutlierEffect createOutlierEffect() {
        return new OutlierEffect();
    }

    /**
     * Create an instance of {@link ExponentialSmoothing }
     * 
     */
    public ExponentialSmoothing createExponentialSmoothing() {
        return new ExponentialSmoothing();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link TrendExpoSmooth }
     * 
     */
    public TrendExpoSmooth createTrendExpoSmooth() {
        return new TrendExpoSmooth();
    }

    /**
     * Create an instance of {@link SeasonalityExpoSmooth }
     * 
     */
    public SeasonalityExpoSmooth createSeasonalityExpoSmooth() {
        return new SeasonalityExpoSmooth();
    }

    /**
     * Create an instance of {@link StateSpaceModel }
     * 
     */
    public StateSpaceModel createStateSpaceModel() {
        return new StateSpaceModel();
    }

    /**
     * Create an instance of {@link StateVector }
     * 
     */
    public StateVector createStateVector() {
        return new StateVector();
    }

    /**
     * Create an instance of {@link TransitionMatrix }
     * 
     */
    public TransitionMatrix createTransitionMatrix() {
        return new TransitionMatrix();
    }

    /**
     * Create an instance of {@link MeasurementMatrix }
     * 
     */
    public MeasurementMatrix createMeasurementMatrix() {
        return new MeasurementMatrix();
    }

    /**
     * Create an instance of {@link PsiVector }
     * 
     */
    public PsiVector createPsiVector() {
        return new PsiVector();
    }

    /**
     * Create an instance of {@link GARCH }
     * 
     */
    public GARCH createGARCH() {
        return new GARCH();
    }

    /**
     * Create an instance of {@link ARMAPart }
     * 
     */
    public ARMAPart createARMAPart() {
        return new ARMAPart();
    }

    /**
     * Create an instance of {@link GARCHPart }
     * 
     */
    public GARCHPart createGARCHPart() {
        return new GARCHPart();
    }

    /**
     * Create an instance of {@link ResidualSquareCoefficients }
     * 
     */
    public ResidualSquareCoefficients createResidualSquareCoefficients() {
        return new ResidualSquareCoefficients();
    }

    /**
     * Create an instance of {@link VarianceCoefficients }
     * 
     */
    public VarianceCoefficients createVarianceCoefficients() {
        return new VarianceCoefficients();
    }

    /**
     * Create an instance of {@link PastVariances }
     * 
     */
    public PastVariances createPastVariances() {
        return new PastVariances();
    }

    /**
     * Create an instance of {@link TreeModel }
     * 
     */
    public TreeModel createTreeModel() {
        return new TreeModel();
    }

    /**
     * Create an instance of {@link MeanClusterDistances }
     * 
     */
    public MeanClusterDistances createMeanClusterDistances() {
        return new MeanClusterDistances();
    }

    /**
     * Create an instance of {@link VariableWeight }
     * 
     */
    public VariableWeight createVariableWeight() {
        return new VariableWeight();
    }

    /**
     * Create an instance of {@link PMML }
     * 
     */
    public PMML createPMML() {
        return new PMML();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link MiningBuildTask }
     * 
     */
    public MiningBuildTask createMiningBuildTask() {
        return new MiningBuildTask();
    }

    /**
     * Create an instance of {@link DataDictionary }
     * 
     */
    public DataDictionary createDataDictionary() {
        return new DataDictionary();
    }

    /**
     * Create an instance of {@link DataField }
     * 
     */
    public DataField createDataField() {
        return new DataField();
    }

    /**
     * Create an instance of {@link TransformationDictionary }
     * 
     */
    public TransformationDictionary createTransformationDictionary() {
        return new TransformationDictionary();
    }

    /**
     * Create an instance of {@link INTSparseArray }
     * 
     */
    public INTSparseArray createINTSparseArray() {
        return new INTSparseArray();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "Array")
    public JAXBElement<ArrayType> createArray(ArrayType value) {
        return new JAXBElement<ArrayType>(_Array_QNAME, ArrayType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Integer }{@code >}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Integer }{@code >}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "Indices")
    public JAXBElement<List<Integer>> createIndices(List<Integer> value) {
        return new JAXBElement<List<Integer>>(_Indices_QNAME, ((Class) List.class), null, ((List<Integer> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "REAL-Entries")
    public JAXBElement<List<Double>> createREALEntries(List<Double> value) {
        return new JAXBElement<List<Double>>(_REALEntries_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "SpectralAnalysis")
    public JAXBElement<String> createSpectralAnalysis(String value) {
        return new JAXBElement<String>(_SpectralAnalysis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "SeasonalTrendDecomposition")
    public JAXBElement<String> createSeasonalTrendDecomposition(String value) {
        return new JAXBElement<String>(_SeasonalTrendDecomposition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Integer }{@code >}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Integer }{@code >}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.dmg.org/PMML-4_4", name = "INT-Entries")
    public JAXBElement<List<Integer>> createINTEntries(List<Integer> value) {
        return new JAXBElement<List<Integer>>(_INTEntries_QNAME, ((Class) List.class), null, ((List<Integer> ) value));
    }

}
